@ECHO OFF
@set OLDDIR=%CD%

REM DISKPART - check drive letters 
cd C:\DRBC\Scripts\Diskpart
diskpart.pl -m check_rw_all_volumes -d DEFGHIJKLMN
diskpart.pl -m check_volumes_letters -d DEFGHIJKLMN
if %ERRORLEVEL% == 0 GOTO STARTWINSERVICES
ECHO CANNOT START WINDOWS SERVICES
GOTO END

:STARTWINSERVICES
ECHO START WINDOWS SERVICES

ECHO START SERVICE ### SPAWNER ###
net stop spawner /y
SET RETRY=10
:WAIT1
net start spawner
ECHO ERRORLEVEL %ERRORLEVEL%
if %ERRORLEVEL% == 0 GOTO NEXT1
SET /A RETRY=%RETRY%-1
ECHO SLEEP FOR 5 SEC.
ping localhost -n 5
ECHO TRY AGAIN %RETRY%
if %RETRY% GTR 0 GOTO WAIT1
ECHO SERVICE ### SPAWNER ### CANNOT BE STARTED
:NEXT1

:END
@chdir /d %OLDDIR%
